export type ProductProps = {
  id: number;
  name: string;
  slug: string;
  description: string;
  category: string;
  sku: string;
  price: number;
  costPrice: number;
  supplierInfo: {
    name: string;
    email: string;
    phone: string;
    country: string;
    city: string;
    description?: string;
    address?: string;
    website?: string;
  };
  countInStock: number;
  currentCount: number;
  soldCount: number;
  image: string;
};

export const products: ProductProps[] = [
  {
    id: 1,
    name: "Acer SLIM",
    slug: "acer-slim",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 2530,
    costPrice: 1900,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier one",
      email: "mail@example-one.com",
      phone: "1234567890",
      country: "Singapore",
      city: "Singapore",
      website: "https://example-one.com",
      address: "897 Example Street, 123-456",
    },
    countInStock: 15,
    currentCount: 5,
    soldCount: 10,
    image: "/acer_slim.png",
  },
  {
    id: 2,
    name: "Acer Xtreme",
    slug: "acer-xtreme",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 2920,
    costPrice: 2100,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier two",
      email: "contact@example-two.com",
      phone: "1234567890",
      country: "USA",
      city: "New York",
      website: "https://example-two.com.cn",
      address: "123 Example Street",
    },
    countInStock: 19,
    currentCount: 14,
    soldCount: 5,
    image: "/acer.png",
  },
  {
    id: 3,
    name: "Dell All-in-one",
    slug: "dell-all-in-one",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3130,
    costPrice: 2200,
    sku: "sku-123",
    category: "Computer",
    supplierInfo: {
      name: "Supplier three",
      email: "overseas@example-three.com",
      phone: "1234567890",
      country: "China",
      city: "Beijing",
      website: "https://example-three.com",
      address: "654 Example Street,Beijing",
    },
    countInStock: 45,
    currentCount: 30,
    soldCount: 15,
    image: "/all-in-one-pc.png",
  },
  {
    id: 4,
    name: "Apple Smart Watch",
    slug: "apple-smart-watch",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 990,
    costPrice: 350,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier four",
      email: "sales@example-four.com",
      phone: "1234567890",
      country: "USA",
      city: "New York",
      website: "https://example-four.com",
      address: "143 Example Street,NY",
    },
    countInStock: 30,
    currentCount: 20,
    soldCount: 10,
    image: "/apple_smartwatch1.png",
  },
  {
    id: 5,
    name: "Apple Smart Watch",
    slug: "apple-smart-watch",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1200,
    costPrice: 780,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/apple-smartwatch.png",
  },

  {
    id: 6,
    name: "Apple Smart Watch",
    slug: "apple-smart-watch",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1200,
    costPrice: 780,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/apple-smrtwatch.png",
  },
  {
    id: 7,
    name: "Asus",
    slug: "asus-desktop",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3200,
    costPrice: 1780,
    sku: "sku-123",
    category: "Computer",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/desktop_asaus.png",
  },
  {
    id: 8,
    name: "Edific",
    slug: "edific-watch",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 200,
    costPrice: 90,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/edific_watch.png",
  },
  {
    id: 9,
    name: "JBL Headphone",
    slug: "jbl-headphone",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 600,
    costPrice: 280,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/headphone_blue-jbl.png",
  },
  {
    id: 10,
    name: "Intex Subsystem",
    slug: "intex-subsystem",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1200,
    costPrice: 780,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/intex_subwoffer.png",
  },
  {
    id: 11,
    name: "Intex Twiter",
    slug: "intex-twiter",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1200,
    costPrice: 780,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/intex_twiter.png",
  },
  {
    id: 12,
    name: "iPhone 13 Pro",
    slug: "iphone-13-pro",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 4200,
    costPrice: 2380,
    sku: "sku-123",
    category: "Phone",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/iPhone13-pro.png",
  },
  {
    id: 13,
    name: "iPhone 13",
    slug: "iphone-13",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3800,
    costPrice: 1980,
    sku: "sku-123",
    category: "Phone",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/iPhone13.png",
  },
  {
    id: 14,
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 6800,
    costPrice: 3980,
    sku: "sku-123",
    category: "Phone",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/iPhone14-pro.png",
  },
  {
    id: 15,
    name: "iPhone 14",
    slug: "iphone-14",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 5800,
    costPrice: 2280,
    sku: "sku-123",
    category: "Phone",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/iPhone14.png",
  },
  {
    id: 16,
    name: "JBL Blast",
    slug: "jbl-blast",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3500,
    costPrice: 2180,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/jbl_blast.png",
  },
  {
    id: 16,
    name: "JBL Boom",
    slug: "jbl-boom",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 400,
    costPrice: 270,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/jbl_boom-black.png",
  },
  {
    id: 17,
    name: "JBL Boom",
    slug: "jbl-boom-colored",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 230,
    costPrice: 170,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/jbl_boom-colored.png",
  },
  {
    id: 17,
    name: "JBL Boom 2",
    slug: "jbl-boom-red",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 400,
    costPrice: 270,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/jbl_boom-red.png",
  },
  {
    id: 18,
    name: "JBL Headphone",
    slug: "jbl-headphone",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 200,
    costPrice: 110,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/jnl_headphone-black.png",
  },
  {
    id: 19,
    name: "Lenovo",
    slug: "lenovo-amd",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3900,
    costPrice: 1780,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/lenovo_amd.png",
  },
  {
    id: 20,
    name: "Lenovo Rizon",
    slug: "lenovo-rizon",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3700,
    costPrice: 1780,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/lenovo-rizon.png",
  },
  {
    id: 21,
    name: "MacBook Workbook",
    slug: "macbook-workbook",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 4700,
    costPrice: 1780,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/macbook_work.jpg",
  },
  {
    id: 22,
    name: "MacBook Pro",
    slug: "macbook-pro",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 5700,
    costPrice: 1980,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/macbook-pro.png",
  },
  {
    id: 23,
    name: "MacBook Air",
    slug: "macbook-air",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 3900,
    costPrice: 2180,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/macbookAir.jpg",
  },
  {
    id: 24,
    name: "Dell Monitor",
    slug: "dell-monitor",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1990,
    costPrice: 1180,
    sku: "sku-123",
    category: "Monitor",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/monitor_curved.png",
  },
  {
    id: 25,
    name: "Dell Monitor",
    slug: "dell-monitor1",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1990,
    costPrice: 1180,
    sku: "sku-123",
    category: "Monitor",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/monito_curved1.png",
  },
  {
    id: 26,
    name: "Lenovo Monitor",
    slug: "lenovo-monitor",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 900,
    costPrice: 280,
    sku: "sku-123",
    category: "Monitor",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/monitor_flat.png",
  },
  {
    id: 27,
    name: "Philips Speaker",
    slug: "philips-speaker",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1900,
    costPrice: 1180,
    sku: "sku-123",
    category: "Electronics",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/philips_spker.png",
  },
  {
    id: 28,
    name: "Apple Smartwatch",
    slug: "apple-smartwatch",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 900,
    costPrice: 190,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/samrt-watch.png",
  },
  {
    id: 29,
    name: "Apple Smartwatch Black",
    slug: "apple-smart-watch-black",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 900,
    costPrice: 190,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/smartwatch-black.png",
  },
  {
    id: 30,
    name: "Apple Smartwatch",
    slug: "apple-smart-watch-one",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 900,
    costPrice: 190,
    sku: "sku-123",
    category: "Watch",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/smartwatch.png",
  },
  {
    id: 31,
    name: "Samsung Slim",
    slug: "samsung-laptop",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1900,
    costPrice: 1180,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/samsung.png",
  },
  {
    id: 32,
    name: "Xiomi Slim",
    slug: "xiomi-laptop",
    description: `Lorem1 Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Veniam recusandae eos quia minus quae perferendis!`,
    price: 1900,
    costPrice: 1180,
    sku: "sku-123",
    category: "Laptop",
    supplierInfo: {
      name: "Supplier five",
      email: "admin@example-five.com",
      phone: "1234567890",
      country: "Japan",
      city: "Tokyo",
      website: "https://example-five.com.jp",
      address: "100 Example Street,JP",
    },
    countInStock: 25,
    currentCount: 15,
    soldCount: 5,
    image: "/xiomi-slim.png",
  },
];
